Feature/exercicio1
GabrielSgrancio/orion-bootcamp-exercicios pull request #1
Opened 2023-10-12 01:19 UTC by GabrielSgrancio

Solução do exercício 1, fiz um html para testar a função também.

Assim que puderem espero o feedback, obrigado

2023-10-12 03:24 UTC, samuelcamilocosta requested changes

2023-10-12 03:24 UTC, samuelcamilocosta commented on exercicio-1.ts
> +function contarVogais(palavra: string): number {
Remova as linhas em branco deixadas entre o comentário do TSDoc e a função

2023-10-12 03:24 UTC, samuelcamilocosta commented on exercicio-1.ts
> +    const vogais = 'aeiouAEIOU';
Adicione a tipagem da variável vogais

2023-10-12 03:24 UTC, samuelcamilocosta commented on exercicio-1.ts
> +    let contador = 0;
Adicione a tipagem da variável contador

2023-10-12 03:24 UTC, samuelcamilocosta commented on exercicio-1.ts
> +* Exemplo de uso da função :
Sugestão: Adicionar esse comentário com TSDoc para tornará seu código visualmente mais elegante por conta da indentação do comentário mais elegante, a linha 24 acaba não sendo necessária e poderia ser removida também

2023-10-12 03:24 UTC, samuelcamilocosta commented on exercicio-1.ts
> +const quantidadeDeVogais = contarVogais(palavraExemplo);
Adicione a tipagem esperada em palavraExemplo e quantidadeDeVogais

2023-10-13 20:26 UTC, GabrielSgrancio commented on index.html
> +        function contarVogais() {
Resolvi esse problema, pode ver agora por favor?

Agora o programa aceita vogais com acento e o script está direcinado para  o arquivo .js

2023-10-13 22:07 UTC, samuelcamilocosta commented on exercicio-1.ts
> +function contarVogais() {
faltou adicionar a tipagem do retorno esperado pela função

2023-10-13 22:07 UTC, samuelcamilocosta commented on exercicio-1.ts
> +/**
O @example normalmente é utilizado para demonstrar um exemplo de uso da função em que se está documentando com o TSDoc.
Nesse caso, pode remover o texto da linha 24 a 26

2023-10-13 22:14 UTC, GabrielSgrancio commented on exercicio-1.ts
> +/**
Beleza, removi. adicionei o tipo {Number} no @return da função

2023-10-14 02:15 UTC, merged