exercicio 2 concluido
GabrielSgrancio/orion-bootcamp-exercicios pull request #2
Opened 2023-10-13 17:00 UTC by GabrielSgrancio

Fiz o push do exercicio 2, tentei o TSDOC e mostrar de acordo com o paradigma imperativo e funcional.

2023-10-13 22:21 UTC, samuelcamilocosta requested changes

2023-10-13 22:21 UTC, samuelcamilocosta commented on exercise-2.ts
> +/*Teste no paradigma funcional*/
As funções que você criou, elas correspondem ao método de paradigma imperativo.
São abordagens que utilizam um for convencional com instruções descritivas.

O paradigma funcional teria uma utilização de métodos funcionais, alguns muito comuns vistos são findIndex, find, filter, forEach, map, entre tantos outros.

Vou deixar um link que aborda um pouco sobre o tema
https://medium.com/tableless/entendendo-programa%C3%A7%C3%A3o-funcional-em-javascript-de-uma-vez-c676489be08b

2023-10-13 22:21 UTC, samuelcamilocosta commented on exercise-2.ts
> +function paradigmaImperativo() {
faltou adicionar a tipagem do retorno esperado pela função de paradigmaImperativo

2023-10-13 22:35 UTC, samuelcamilocosta requested changes

2023-10-13 22:35 UTC, samuelcamilocosta commented on exercise-2.ts
> +    let bio = getBio(1);
utilizar const ao invés de let em bio e name

2023-10-14 02:08 UTC, samuelcamilocosta requested changes

2023-10-14 02:08 UTC, samuelcamilocosta commented on exercise-2.ts
> +function paradigmaImperativo(): void {
Adicione a documentação TSDoc para a função de paradigmaImperativo

2023-10-14 02:08 UTC, samuelcamilocosta commented on exercise-2.ts
> +const getBioFuncional = (id: number): string | undefined => {
Adicione documentação TSDoc as arrow functions getBioFuncional, getNameFuncional, deleteItemFuncional, updateBioOrNameFuncional.

2023-10-14 12:40 UTC, alan-rocha-newrizon approved these changes

2023-10-14 12:40 UTC, merged